# Generated by Django 3.2.9 on 2021-11-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=225)),
                ('Password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankac_id', models.IntegerField()),
                ('Bank_name', models.CharField(max_length=225)),
                ('Total_balance', models.FloatField()),
                ('Budget', models.FloatField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=225)),
                ('dob', models.DateField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income', models.FloatField()),
                ('Otherpay', models.FloatField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Total', models.FloatField()),
                ('Bankac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.bank')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Bankac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.bank')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category')),
            ],
        ),
    ]
